# Site settings
title: Danyel Fisher
author: Danyel FIsher
email: danyelf@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  Danyel Fisher: Visualization Reearcher
  Interested in Data Visualization and Databases.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.danyelfisher.info" # the base hostname & protocol for your site
twitter_username: fisherdanyel
github_username:  danyelf

# Google Analytics
google_analytics_tracking_id: 

sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-feed
